### ISSUE TITLE
Compatibility EXT:invisiblerecaptcha with EXT:powermail > 5.x

### ISSUE THREAD

**Issue by angeloprevitali** [einpraegsam/invisiblerecaptcha#2]
Hello Alex

due to your EXT:powermail is already on version 5.3.1 it seems that your extension invisiblerecaptcha isn't compatible with your actual powermail, right?

If i install bough extension EXT:powermail 5.3.1 and EXT:invisiblerecaptcha 1.1.1 on the FE output there is only a PHP error coming.

Are there any plans concerning adapting your ext with EXT:powermail > 5?

Thanks for feedback.

Regards,
Angelo

**Comment by einpraegsam** [comment]
I just released 2.0.0 for powermail 5.x - have fun
