### ISSUE TITLE
how to apply with multilanguage - multidamains?

### ISSUE THREAD

**Issue by hocomadvies** [einpraegsam/invisiblerecaptcha#23]
How to apply the invisible-recaptcha when having a multi-language site, where each language has its own domain- url? So there are 3 google-key codes created one for each domain. The form is also translated for the 3 languages.

<img width="1144" alt="Scherm­afbeelding 2023-09-26 om 15 12 49" src="https://github.com/einpraegsam/invisiblerecaptcha/assets/10847395/196058ae-d75e-4087-82b2-ee669089978b">

**Comment by einpraegsam** [comment]
There are some answers to this in the slack channel ext-powermail. Short answer: Use conditions for different domains.
