### ISSUE TITLE
reCAPTCHA kann nicht erreicht werden. Überprüfen Sie die Verbindung und versuchen Sie es erneut.

### ISSUE THREAD

**Issue by kiwi2101** [einpraegsam/invisiblerecaptcha#4]
Suddenly I get the error "reCAPTCHA kann nicht erreicht werden. Überprüfen Sie die Verbindung und versuchen Sie es erneut." Anyone with this issue? Is this a problem of this extension or Google reCaptcha itself? Any help would be appreciated.

**Comment by cweiske** [comment]
This is not a problem with the extension. Here it works fine.
Most likely some connectivity issue with your internet connection.

**Comment by einpraegsam** [comment]
Thx for the feedback
