### ISSUE TITLE
"Submit" button title is hard-coded

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/invisiblerecaptcha#5]
There is currently no way to change the "Submit" button title, which is not nice for e.g. German sites.

**Comment by einpraegsam** [comment]
When I look at https://github.com/einpraegsam/invisiblerecaptcha/blob/master/Resources/Private/Partials/Form/Field/Invisiblerecaptcha.html#L12 it is not hardcoded but the title of the field

**Comment by cweiske** [comment]
Oh. I only looked at the local code which is version 1.1.0 (because we're on TYPO3 7.6).

Sorry.
