### ISSUE TITLE
AJAX validation

### ISSUE THREAD

**Issue by DTM-TYPO3** [einpraegsam/invisiblerecaptcha#6]
Is it possible to validate the form via AJAX? I´ve set the powermail option **plugin.tx_powermail.settings.setup.misc.ajaxSubmit = 1** 
but it doesn´t work with invisiblerecaptcha and  confirmation-option.
But that would be great :-)
Thanks in advance!
Stefanie

**Comment by einpraegsam** [comment]
AJAX validation is not yet supported - sorry
